# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  DiskEMU_config = debug_win64

else ifeq ($(config),release_win64)
  DiskEMU_config = release_win64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := DiskEMU

.PHONY: all clean help $(PROJECTS) Tools

all: $(PROJECTS)

Tools: DiskEMU

DiskEMU:
ifneq (,$(DiskEMU_config))
	@echo "==== Building DiskEMU ($(DiskEMU_config)) ===="
	@${MAKE} --no-print-directory -C tools/diskemu -f Makefile config=$(DiskEMU_config)
endif

clean:
	@${MAKE} --no-print-directory -C tools/diskemu -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  release_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DiskEMU"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"