# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  DiskEMU_config = debug_win64
  Debugger_config = debug_win64
  kernel_config = debug_win64

else ifeq ($(config),release_win64)
  DiskEMU_config = release_win64
  Debugger_config = release_win64
  kernel_config = release_win64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := DiskEMU Debugger kernel

.PHONY: all clean help $(PROJECTS) Kernel Tools

all: $(PROJECTS)

Kernel: kernel

Tools: Debugger DiskEMU

DiskEMU:
ifneq (,$(DiskEMU_config))
	@echo "==== Building DiskEMU ($(DiskEMU_config)) ===="
	@${MAKE} --no-print-directory -C tools/diskemu -f Makefile config=$(DiskEMU_config)
endif

Debugger:
ifneq (,$(Debugger_config))
	@echo "==== Building Debugger ($(Debugger_config)) ===="
	@${MAKE} --no-print-directory -C tools/debugger -f Makefile config=$(Debugger_config)
endif

kernel:
ifneq (,$(kernel_config))
	@echo "==== Building kernel ($(kernel_config)) ===="
	@${MAKE} --no-print-directory -C kernel -f Makefile config=$(kernel_config)
endif

clean:
	@${MAKE} --no-print-directory -C tools/diskemu -f Makefile clean
	@${MAKE} --no-print-directory -C tools/debugger -f Makefile clean
	@${MAKE} --no-print-directory -C kernel -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  release_win64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DiskEMU"
	@echo "   Debugger"
	@echo "   kernel"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"